version: '3.8'
services:
  postgres_database:
    image: postgres
    container_name: postgres_database
    env_file:
        - .env
    ports:
        - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
