# Generated by Django 4.1.4 on 2023-10-13 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_title', models.CharField(default='', max_length=100)),
                ('query_description', models.CharField(max_length=1000)),
                ('query_date', models.DateField()),
                ('query_time', models.TimeField()),
                ('query_status', models.BooleanField(default=False)),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
