# Generated by Django 3.2.12 on 2022-12-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_end', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='query_info',
            new_name='query_description',
        ),
        migrations.AddField(
            model_name='query',
            name='query_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='query',
            name='query_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
